name: ZEngine Cmake Linux Workflow

on:
  workflow_call:
    inputs:
      configuration:
        type: string
        default: 'Debug'
      targetFramework:
        type: string
        default: 'net8.0'

env: 
  USERNAME: mathewbensoncode
  VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg
  FEED_URL: https://nuget.pkg.github.com/mathewbensoncode/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/mathewbensoncode/index.json,readwrite"
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

jobs:
  Linux-Build:
    name: cmake-build-linux-${{ inputs.configuration }}
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      
    - name: Download the Microsoft repository GPG keys
      run: wget -q https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb

    - name: Register the Microsoft repository GPG keys
      run: sudo dpkg -i packages-microsoft-prod.deb

    - name: Install LLVM-22
      run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22

    - name: Update the list of packages
      run: sudo apt-get update

    - name: Install Dependencies
      run: sudo apt-get install libasound2-dev libgl1-mesa-dev libpulse-dev libdbus-1-dev libx11-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxrandr-dev libxss-dev libxt-dev libxxf86vm-dev cmake apt-transport-https software-properties-common gcc g++ powershell clang-format-22 libxkbcommon-dev mono-complete

    - name: Install vcpkg
      shell: pwsh
      run: git clone https://github.com/Microsoft/vcpkg ${{github.workspace}}/vcpkg

    - name: Bootstrap vcpkg
      shell: pwsh
      run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

    - name: Add NuGet sources
      shell: pwsh
      run: |
        .$(${{ env.VCPKG_EXE }} fetch nuget) `
        sources add `
        -Source "${{ env.FEED_URL }}" `
        -StorePasswordInClearText `
        -Name GitHubPackages `
        -UserName "${{ env.USERNAME }}" `
        -Password "${{ secrets.GITHUB_TOKEN }}"
        .$(${{ env.VCPKG_EXE }} fetch nuget) `
        setapikey "${{ secrets.GITHUB_TOKEN }}" `
        -Source "${{ env.FEED_URL }}"

    - name: CMake Build
      run: .\Scripts\BuildEngine.ps1 -Configurations ${{inputs.configuration}}
      shell: pwsh

    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: Build-linux-${{inputs.configuration}}
        if-no-files-found: error
        path: |
          Result.Linux.x64.${{inputs.configuration}}/bin
          Result.Linux.x64.${{inputs.configuration}}/lib/*vulkan*
          Result.Linux.x64.${{inputs.configuration}}/tests
