# @JeanPhilippeKernel : Disabled because we only support Windows as platform for now
#
name: ZEngine Linux Build

on:
  push:
    branches: [ newcmakelinux ]
  pull_request:
    branches: [ master ]

jobs:
  Linux-Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install development library
      run: sudo apt-get install git libasound2-dev libgl1-mesa-dev libpulse-dev libdbus-1-dev libx11-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxrandr-dev libxss-dev libxt-dev libxxf86vm-dev cmake gcc g++ ninja-build libassimp-dev libfmt-dev libimgui-dev libstb-dev libglfw3-dev libspdlog-dev libglm-dev libyaml-cpp-dev libspirv-cross-c-shared-dev spirv-cross spirv-tools googletest

    - name: CMake Build
      run: mkdir ../build && cmake -B ../build -G Ninja && cmake --build ../build
