# @JeanPhilippeKernel : Disabled because we only support Windows as platform for now
#
name: ZEngine Linux Build

on:
  push:
    branches: [ newcmakelinux ]
  pull_request:
    branches: [ master ]

jobs:
  Linux-Build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install development library
      run: sudo apt-get update && sudo apt-get install -y git libasound2-dev libgl1-mesa-dev libpulse-dev libdbus-1-dev libx11-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxrandr-dev libxss-dev libxt-dev libxxf86vm-dev cmake gcc g++ ninja-build libassimp-dev libfmt-dev libimgui-dev libstb-dev libglfw3-dev libspdlog-dev libglm-dev libyaml-cpp-dev libspirv-cross-c-shared-dev spirv-cross spirv-tools glslang-dev glslang-tools nlohmann-json3-dev dotnet-runtime-8.0

    - name: Create CMake Build Directory
      run: mkdir ../build && cmake -B ../build -DCMAKE_BUILD_TYPE=Debug -G Ninja

    - name: Build
      run: cmake --build ../build

    - name: Test
      run: ctest .
      working-directory: ../build/ZEngine/tests
