name: ZEngine Window CMake Build

on:
  push:
branches: [ newcmakelinux ]

jobs:
  Windows-CMake-Build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create CMake Build Directory
        shell: pwsh
        run: mkdir ../build && cmake -B ../build -DCMAKE_BUILD_TYPE=Debug -G Ninja

      - name: Build
        shell: pwsh
        run: cmake --build ../build

      - name: Test
        shell: pwsh
        run: ctest .
        working-directory: ../build/ZEngine/tests


