name: ZEngine Window CMake Build

on:
  push:
    branches: [ newcmakelinux ]

jobs:
  Windows-CMake-Build:
    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create CMake Build Directory
      run: mkdir ../build && cmake -B ../build -DCMAKE_BUILD_TYPE=Debug -G Ninja

    - name: Build
      run: cmake --build ../build

    - name: Test
      run: ctest .
      working-directory: ../build/ZEngine/tests


